load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "fn1",
    srcs = ["fn1.go"],
    importpath = "aspect.build/gazelle/gazelle/common/fn1",
    visibility = ["//visibility:public"],
)

go_test(
    name = "fn1_test",
    srcs = ["fn1_test.go"],
    embed = [":fn1"],
    deps = ["@com_github_google_go_cmp//cmp"],
)
