package fn1

import (
	"fmt"
	"iter"
)

// Map applies the given function to each element of the input sequence
// and returns a new sequence containing the results.
func Map[T, R any](values iter.Seq[T], transform func(elem T) R) iter.Seq[R] {
	return iter.Seq[R](func(yield func(R) bool) {
		for elem := range values {
			if !yield(transform(elem)) {
				return
			}
		}
	})
}

// AssociateBy builds a map from the elements of the input sequence,
// using the provided keySelector function to extract keys.
//
// If multiple elements have the same key, the function panics.
func AssociateBy[T any, K comparable](
	values iter.Seq[T],
	keySelector func(T) K,
) map[K]T {
	result := make(map[K]T)
	for elem := range values {
		key := keySelector(elem)
		value := elem
		if _, exists := result[key]; exists {
			panic(fmt.Errorf("duplicate keys generated by AssociateBy: %v", key))
		}
		result[key] = value
	}
	return result
}
